### ISSUE TITLE
Template: should include mode variable

### ISSUE THREAD

**Issue by rot26** [cloudmitigator/reflex-cli#79]
Reflex version:

```
reflex --version
reflex, version 0.7.8
```

It looks like the template does not include mode in the variables, so when it's called as a module with a mode variable, it will fail.

Example module file generated by `reflex init` (and my inputs)

```tf
module "reflex-aws-detect-cloudwatch-alarms-deleted" {
  source            = "git::https://github.com/cloudmitigator/reflex-aws-detect-cloudwatch-alarms-deleted.git?ref=develop-cw-alrams-deleted"
  sns_topic_arn     = module.central-sns-topic.arn
  reflex_kms_key_id = module.reflex-kms-key.key_id
  mode              = "detect"
}
```

So when running a `terraform plan`, using the default generated template, we will throw an error.

```STDOUT
Error: Unsupported argument

  on reflex-aws-detect-cloudwatch-alarms-deleted.tf line 5, in module "reflex-aws-detect-cloudwatch-alarms-deleted":
   5:   mode              = "detect"

An argument named "mode" is not expected here.
```

**Comment by mcbanderson** [comment]
The current assumption is that the `mode` variable will only be declared if the rule is capable of being in `remediate` mode. If the rule is a `notify` only rule, mode should not be specified. The reason for this is we're currently using the presence (or absence) of the `mode` variable in `variables.tf` to determine whether or not a Rule is capable of being a `remediate` Rule.

This is definitely not a particularly robust solution (as you clearly experienced). If you have a recommendation on how we could handle this better let me know.

**Comment by rot26** [comment]
So to clarify the error case here, I generated this template as a detect, which is fine.  It's generates the template just fine (it's quite nice actually).  The template does not include  `variable "mode" {` we expect.  All clear so far.

This error shows up after doing a `reflex int` and `reflex build`, and the `mode='detect'` shows up anyway.

```tf
  mode              = "detect"
```

**Comment by mcbanderson** [comment]
Hmm, what does your `reflex.yaml` config look like for the rule? Is `mode` included as a configuration item there? `reflex build` will take any configuration item in `reflex.yaml` and include it in your built `tf` files. That might be the issue.

The idea for the current setup is the manifest generator will look in `variables.tf` for `mode`, and then copy that (or not) into the manifest file. `reflex init` will then use the manifest file to know whether or not to include `mode` in `reflex.yaml` for each rule.

This is all basically a very convoluted way of trying to automatically indicate to users whether or not they can activate `remediate` mode for a rule. If `reflex init` includes `mode` in the configuration, they can switch the value to `remediate` if they choose. If `mode` isn't present they can't, and including it will cause a failure (as you've discovered).

Definitely open to alternatives if you have any ideas as to how we could better handle it.

**Comment by rot26** [comment]
Notes to myself:  It's getting added as configurables:

https://github.com/cloudmitigator/reflex-cli/blob/master/reflex_cli/templates/aws-rule.tf#L5-L11

Is there a problem with the mode being set to "detect" for this?

**Comment by rot26** [comment]
Ok, duh, mode was passed in at the reflex.yaml level

```yaml
rules:
- reflex-aws-detect-cloudwatch-alarms-deleted:
    configuration:
    - mode: "detect"
    version: develop-cw-alrams-deleted
```

**Comment by rot26** [comment]
But... if we're taking the stance that "mode:detect" will be in our reflex file by default, shouldn't we also include that in `variables.tf`?

**Comment by rot26** [comment]
My suggestion for Option 1 is to allow the mode variable in the newly created rule.  We could do this by not inspecting the "remediate" conditional.

https://github.com/cloudmitigator/reflex-cli/blob/master/reflex_cli/templates/rule_templates/variables.tf#L11-L17

**Comment by rot26** [comment]
Also, in the command line, we have "NOTIFY" and "REMEDIATE".  In this notes here we have "DETECT" and "REMEDIATE".  We should probably standardize on this terminology.

**Comment by mcbanderson** [comment]
Good catch on the inconsistency, I like `DETECT` over `NOTIFY` personally.

> if we're taking the stance that "mode:detect" will be in our reflex file by default
Right now we're taking the opposite stance. `mode: detect` (or `mode: remediate`) will only be in the reflex file if the rule is capable of being in `remediate` mode.

If we went the route you're suggesting of including `mode` as a variable in all rules, we'd have to come up with a different way to programmatically determine if a rule is capable of being in `remediate` mode and communicating that to users. It would also mean that if someone incorrectly tried to put a rule in `remediate` mode when that isn't supported, the rule would only fail at runtime instead of on deployment, which is less than ideal.

**Comment by rot26** [comment]
I confirmed on reflex-cli 0.7.10 that I needed to remove the line `mode:` in for the rule in `reflex.yaml`

Closing this issue. 
Thanks @mcbanderson .
